version: '2'
services:
  onlinestore1-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/onlinestore1/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=onlinestore1
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
